# Generated by Django 5.0 on 2025-06-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "7. Order Items",
            },
        ),
    ]
