# Generated by Django 5.0 on 2025-06-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
